### ISSUE TITLE
from_env is not from environment variables?

### ISSUE THREAD

**Issue by rich-murphey** [google/argh#6]
It's not obvious from the readme that from_env() does not take input from environment variables.  This may be confusing for first time readers of this documentation.  Note that the 'env' term has popular usage to mean environment variables in the 'env', env_logger, and dotenv crates.  

I think the documentation is great, so this isn't intended as critical, but rather an attempt to highlight the challenge for newcomers to rust, who may struggle to understand the meaning of various documentation.

**Comment by cavedweller** [comment]
Several other argument parsers in the Rust ecosystem already use the `from_env` convention. 

Example: https://github.com/RazrFalcon/pico-args#alternatives

I'd prefer to not break the existing consumers of the library, which exist since this has been used for many months internally, but I'd consider adding a `from_args` or equivalent if you think that would be less confusing.

**Comment by rich-murphey** [comment]
Ah, thanks for clarifying the president.
That sounds reasonable, so I'm closing this.
